### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by ghost** [Szpachlarz/book-db-gui#1]
2 questions

1 - is it available in english?

2 - why the login screen? can't it simply let you edit your database from the start?

**Comment by Szpachlarz** [comment]
Hello, sorry for the late response.

It's a student project for a university assignment, that's why we made a login screen - it was mandatory. It isn't available in English, because I don't think it's worth it. I'm surprised that somebody has found this project and looked into it.

**Comment by ghost** [comment]
> Hello, sorry for the late response.
> 
> It's a student project for a university assignment, that's why we made a login screen - it was mandatory. It isn't available in English, because I don't think it's worth it. I'm surprised that somebody has found this project and looked into it.

I see. I was searching for a book database to organize my book collection, and I came across this program. I found some other ones but they all require SQL databases and I just want a regular program with no SQL
